export enum PlayerState {
    IDLE = 'IDLE',
    RUN = 'RUN',
    ATTACK_PRIMARY = 'ATTACK_PRIMARY',
    CASTING_SECONDARY = 'CASTING_SECONDARY',
    CHANNELING_SPECIAL = 'CHANNELING_SPECIAL',
    STUNNED = 'STUNNED'
}
